services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    command: 
      - --max_connections=100
      - --wait_timeout=600
      - --interactive_timeout=600
      - --innodb_buffer_pool_size=1G
      - --innodb_log_buffer_size=256M
      - --innodb_log_file_size=512M
      - --innodb_write_io_threads=8
      - --innodb_read_io_threads=8
      - --tmp_table_size=64M
      - --max_heap_table_size=64M
      - --bind-address=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: 